### ISSUE TITLE
TodosList screen

### ISSUE THREAD

**Issue by pteasima** [baddazi/TodoList#2]
- Always make sure to use good naming. Im assuming the app was named "Todos" or similar, we'll be calling everything "Todo...." based on that. If, for example, you named the app "Tasks", adjust the naming of everything else accordingly.
- Make sure to keep updating this Issue description, adding your own checklist items etc., generally stay organized. I must see that you have potential to not become messy and manage yourself, so that I can ease off and only help with technical stuff. Don't hesitate spending time learning to use github's project managements features well. Btw Im not sure if you can edit my comment, so if not, add your own comment and stay organized there.
- [x] create a new branch from development called `feature/todos-list`
- [x] Add a new SwiftUI view `TodosListView` (`TodosListView.swift` file)
- [x] Remove `ContentView.swift`, use `TodosListView` in `TodosApp`'s `body`.
- [x] Make sure you can display something in the list
  - so e.g. `TodosListView.body` could be
  ```
  List {
  Text("test list item")
  }
  ```
- [x] Create the `Todo` model (`Todo.swift`). For now it looks like this:
```
struct Todo {
  var createdAt: Date
}
```
- [x] add `@State var todos: [Todo] = []` into `TodosListView`
- [x] Show some todos in the list (your `let testData...` was okay.)
  - a better abstraction might be
  ```
  extension Todo {
    static var sample: Self = .init(createdAt: .distantPast)
    static var sample2: Self = .init(createdAt: .distantFuture)
  }
  ```
  - use any dates you want, but not `Date()`, we want our sample data to be static, not change everytime we run the app.
  - don't use `#if DEBUG` around these, they could actually be useful in production for setting up redacted UI (not important now)
  - You could have a `sampleTodos` array somewhere, either globally or `extension Array where Element == Todo { static var sampleTodos.... }`, but I don't think its needed.
  - Don't have too much test data, you'll have to always update it as your model changes, one or two samples should be all you need, can always create more on the spot if needed.
  - You can add Identifiable conformance if you want (not needed but probably reasonable), but don't add a randomly generated UUID yet (you can uniquely identify a `Todo` using the time it was created). We might need the UUID at some point, but we're trying to keep everything as small and simple as possible.
- [x] add a plus button to the top right of TodoListView.
  - [ ] This will be a "trailing navigation item", find out what that is, realize that you need a "navigation bar" to put it into, make that happen.
 - [x] Also make your navigation bar display the title "Todos".
 - [x] When the plus button is tapped, a `Todo` with `createdAt` set to the current date should be added to the List.
 - [x] Test that everything works as expected.
 - [x] Push your branch.
 - [x] Create a pull request into `development`, make it a "Draft" pull request.
 - [x] Self-review your code. When you're happy with it, change the PR from draft to ready, assign me as reviewer.

**Comment by pteasima** [comment]
@baddazi if you hate the fact that a `Todo` just has a `createdAt` property and doesn't even have a name, you can add a `var name: String` or `var title: String`. But Im trying to work with minimal examples, and we're not quite ready to a TextField where user can type a name (that will be on another screen / another View)

**Comment by baddazi** [comment]
Ideas for application features:

1.  After clicking on the plus button a new blank screen for writing text will appear. The first line will be considered the todo title. The title will be used on the main screen.

2. After clicking on todo element a new screen will appear and text inside will be editable.

3.  After long click ( if long click exist in swift) on todo element the todo title becomes editable, allowing you to change the title only.

4.  After double-tapping the todo element title will be strikethrough and will be included at the end.

5.  Aftet left swing on the todo element the delete option button appears. When pressing button, the todo elemenet will be moved to the trash.

What do you think? @pteasima

**Comment by pteasima** [comment]
@baddazi good thoughts, feel free to turn these into future issues.

- Think for yourself how to divide these into logical chunks - e.g. 1 and 2 seem so similar that they could be done together (maybe we'll even use the same `TodoDetailView` with slight variations when adding new / editing existing todo, but I don't want to presume that)
- 5 is standard behavior using `onDelete` view modifier, should be pretty straightforward.
- 3 and 4 are bad UX. We need to be consistent with iOS platform standards, else users won't know how to use the app. Do you have an iPhone? Can you do state of the art analysis? How does Notes do it? How does Reminders do it? How do third party apps do it? Btw, for the first few weeks/months the UX will always be defined for you by myself or the client, you'll gain experience over time to be able to define your own UX. But fine to spend some time on it if this is interesting to you.
